name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up age (POSIX)
      if: ${{ matrix.os != 'windows-latest' }}
      uses: adnsio/setup-age-action@v1.1.0
      with:
        version: ^1.0.0
    - name: Set up age (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install age.portable
    - name: Test with unittest
      run: |
        age --version
